development:
  adapter: postgresql
  encoding: unicode
  database: vangst_challenge_development
  pool: 5
  username: postgres
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: vangst_challenge_test
  pool: 5
  username: postgres
  password: 